
[env:freenove_esp32_s3_wroom]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
board_build.partitions = partitions.csv

; Make sure to include all the components
extra_scripts =
  pre:tools/configure_esp_idf_components.py

; Build flags for configuration
build_flags =
  -DCONFIG_LWIP_IPV6=0
  -DCONFIG_FREERTOS_HZ=1000
  ; LVGL configurations
  -DLV_CONF_INCLUDE_SIMPLE=1
  -DLV_COLOR_DEPTH=16
  -DLV_COLOR_16_SWAP=1
  ; Increase stack size for LVGL task
  -DCONFIG_LVGL_TASK_STACK_SIZE=8192
  ; SD Card configurations
  -DCONFIG_SDMMC_USE_GPIO_MATRIX=1
  ; Audio configurations
  -DCONFIG_I2S_ISR_IRAM=1
